version: "3.8"

services:
  angular:
    build: frontend # especifique a pasta do Dockerfile
    container_name: coco_bambu_angular
    restart: always
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=dev

  express:
    build: api # especifique a pasta do Dockerfile
    container_name: coco_bambu_express
    restart: always
    ports:
      - "3000:3000"
    environment:
      - SECRET=Thisismysecret
      - MONGO_DB_USERNAME=admin-user
      - MONGO_DB_PASSWORD=admin-password
      - MONGO_DB_HOST=database
      - MONGO_DB_PORT=
      - MONGO_DB_PARAMETERS=?authSource=admin
      - MONGO_DB_DATABASE=coco-bambu
    links:
      - database

  database:
    image: mongo:latest # especificar que imagem usar
    container_name: coco_bambu_mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin-user
      - MONGO_INITDB_ROOT_PASSWORD=admin-password
      - MONGO_DB_USERNAME=admin-user1
      - MONGO_DB_PASSWORD=admin-password1
      - MONGO_DB=coco-bambu
    volumes:
      - ./mongo:/home/mongodb
      - ./mongo/init-db.d/:/docker-entrypoint-initdb.d/
      - ./mongo/db:/data/db
    ports:
      - "27017:27017"

  nginx:
    build: loadbalancer # especifique a pasta do Dockerfile
    container_name: coco_bambu_nginx
    restart: always
    ports:
      - "80:80"
    links:
      - express
      - angular
