version: "3.8"

services:
  angular:
    build: # especifique a pasta do Dockerfile
      context: ./frontend
      dockerfile: debug.dockerfile
    container_name: coco_bambu_angular
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
      - "4200:4200"
      - "49153:49153"
    environment:
      - NODE_ENV=dev

  express:
    build: # especifique a pasta do Dockerfile
      context: ./api
      dockerfile: debug.dockerfile
    container_name: coco_bambu_express
    volumes:
      - ./api:/api
      - /api/node_modules
    ports:
      - "3000:3000"
    environment:
      - SECRET=Thisismysecret
      - NODE_ENV=development
      - MONGO_DB_USERNAME=admin-user
      - MONGO_DB_PASSWORD=admin-password
      - MONGO_DB_HOST=database
      - MONGO_DB_PORT=
      - MONGO_DB_PARAMETERS=?authSource=admin
      - MONGO_DB_DATABASE=coco-bambu
    links:
      - database

  database:
    image: mongo # especificar que imagem usar
    container_name: coco_bambu_mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin-user
      - MONGO_INITDB_ROOT_PASSWORD=admin-password
      - MONGO_DB_USERNAME=admin-user1
      - MONGO_DB_PASSWORD=admin-password1
      - MONGO_DB=coco-bambu # nome do banco de dados

    volumes:
      - ./mongo:/home/mongodb
      - ./mongo/init-db.d/:/docker-entrypoint-initdb.d/
      - ./mongo/db:/data/db
    ports:
      - "27017:27017"
